### ISSUE TITLE
Options don't seem to be passed

### ISSUE THREAD

**Issue by leslc** [gonzalo-espinosa/postcss-autoprefixer-stream#1]
Hi @gonzae, I'm using this package and noticed the options aren't being passed in, especially when trying to change "browsers".

If we change "index.js"
```
postcss([ autoprefixer ])
.process(data, options)
```
to:
```
postcss([ autoprefixer(options) ])
.process(data)
```
the options are passed in.  Are you seeing the same behavior?

Would you be okay if I created a PR for the fix?

Thanks

**Comment by leslc** [comment]
This package is so small, we should just copy this over to use. 😄 Maybe that would be easier.

**Comment by gonzae** [comment]
Hi @leslc. Thanks for reporting! That issue should be fixed right now ;).

**Comment by leslc** [comment]
Thank you @gonzae!
